import Link from "next/link";
import { ArrowRight } from "lucide-react";

export default function AboutSection() {
  return (
      <section className="bg-brand-parchment py-20">
            <div className="container-custom">
                    <div className="grid items-center gap-14 lg:grid-cols-2">
                              {/* Left Content */}
                                        <div>
                                                    <span className="text-sm font-semibold uppercase tracking-[0.3em] text-brand-gold">
                                                                  About High Vision Infra
                                                                              </span>

                                                                                          <h2 className="mt-4 text-3xl font-bold text-brand-emerald sm:text-4xl">
                                                                                                        Building Trust Through Premium Developments
                                                                                                                    </h2>

                                                                                                                                <p className="mt-6 text-gray-600 leading-8">
                                                                                                                                              High Vision Infra is committed to creating premium plotted
                                                                                                                                                            developments with clear documentation, strategic locations,
                                                                                                                                                                          modern infrastructure, and long-term investment value.
                                                                                                                                                                                      </p>

                                                                                                                                                                                                  <p className="mt-4 text-gray-600 leading-8">
                                                                                                                                                                                                                Every project is planned with transparency, quality, and
                                                                                                                                                                                                                              customer satisfaction at its core, ensuring peace of mind
                                                                                                                                                                                                                                            for every buyer.
                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                  href="/about"
                                                                                                                                                                                                                                                                                                className="mt-8 inline-flex items-center gap-2 rounded-xl bg-brand-gold px-6 py-3 text-sm font-semibold text-white transition hover:bg-brand-goldHover"
                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                          Learn More
                                                                                                                                                                                                                                                                                                                                        <ArrowRight className="h-4 w-4" />
                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                        {/* Right Placeholder */}
                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex h-[420px] w-full max-w-[520px] items-center justify-center rounded-3xl border border-brand-border bg-white shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-lg font-medium text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                            About Image
                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
