import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";

const gallery = [
  "/images/gallery/gallery-1.jpg",
    "/images/gallery/gallery-2.jpg",
      "/images/gallery/gallery-3.jpg",
        "/images/gallery/gallery-4.jpg",
          "/images/gallery/gallery-5.jpg",
            "/images/gallery/gallery-6.jpg",
            ];

            export default function GallerySection() {
              return (
                  <section className="bg-brand-parchment py-20">
                        <div className="container-custom">
                                {/* Heading */}
                                        <div className="mb-14 flex flex-col items-start justify-between gap-6 lg:flex-row lg:items-end">
                                                  <div>
                                                              <span className="text-sm font-semibold uppercase tracking-[0.3em] text-brand-gold">
                                                                            Gallery
                                                                                        </span>

                                                                                                    <h2 className="mt-4 text-3xl font-bold text-brand-emerald sm:text-4xl">
                                                                                                                  Explore Our Projects
                                                                                                                              </h2>

                                                                                                                                          <p className="mt-4 max-w-2xl text-gray-600">
                                                                                                                                                        A glimpse of our premium layouts, infrastructure,
                                                                                                                                                                      amenities and communities.
                                                                                                                                                                                  </p>
                                                                                                                                                                                            </div>

                                                                                                                                                                                                      <Link
                                                                                                                                                                                                                  href="/gallery"
                                                                                                                                                                                                                              className="inline-flex items-center gap-2 rounded-xl border border-brand-gold px-5 py-3 text-sm font-semibold text-brand-emerald transition hover:bg-brand-gold hover:text-white"
                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                    View Gallery
                                                                                                                                                                                                                                                                <ArrowRight className="h-4 w-4" />
                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                          {/* Images */}
                                                                                                                                                                                                                                                                                                  <div className="grid grid-cols-2 gap-4 md:grid-cols-3">
                                                                                                                                                                                                                                                                                                            {gallery.map((image) => (
                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                      key={image}
                                                                                                                                                                                                                                                                                                                                                    className="group overflow-hidden rounded-2xl"
                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                              <Image
                                                                                                                                                                                                                                                                                                                                                                                              src={image}
                                                                                                                                                                                                                                                                                                                                                                                                              alt="High Vision Infra Gallery"
                                                                                                                                                                                                                                                                                                                                                                                                                              width={600}
                                                                                                                                                                                                                                                                                                                                                                                                                                              height={500}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="aspect-[4/3] w-full object-cover transition duration-500 group-hover:scale-110"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }