import {
      BadgeCheck,
        ShieldCheck,
          MapPinned,
            Banknote,
            } from "lucide-react";

            const FEATURES = [
              {
                  icon: BadgeCheck,
                      title: "Premium Projects",
                          description:
                                "Carefully planned residential layouts with modern infrastructure and future growth potential.",
                                  },
                                    {
                                        icon: ShieldCheck,
                                            title: "100% Clear Documentation",
                                                description:
                                                      "Verified legal documents with complete transparency for a secure investment.",
                                                        },
                                                          {
                                                              icon: MapPinned,
                                                                  title: "Prime Locations",
                                                                      description:
                                                                            "Projects located near highways, schools, hospitals and rapidly developing areas.",
                                                                              },
                                                                                {
                                                                                    icon: Banknote,
                                                                                        title: "Easy Bank Loans",
                                                                                            description:
                                                                                                  "Loan assistance from leading banks to make your property purchase simple.",
                                                                                                    },
                                                                                                    ];

                                                                                                    export default function WhyChooseUs() {
                                                                                                      return (
                                                                                                          <section className="bg-white py-20">
                                                                                                                <div className="container-custom">
                                                                                                                        {/* Heading */}
                                                                                                                                <div className="mx-auto mb-14 max-w-3xl text-center">
                                                                                                                                          <span className="text-sm font-semibold uppercase tracking-[0.3em] text-brand-gold">
                                                                                                                                                      Why Choose Us
                                                                                                                                                                </span>

                                                                                                                                                                          <h2 className="mt-4 text-3xl font-bold text-brand-emerald sm:text-4xl">
                                                                                                                                                                                      Trusted by Families & Investors
                                                                                                                                                                                                </h2>

                                                                                                                                                                                                          <p className="mt-5 text-gray-600 leading-8">
                                                                                                                                                                                                                      We combine transparency, premium planning and customer-first
                                                                                                                                                                                                                                  service to deliver real estate investments you can trust.
                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                            {/* Cards */}
                                                                                                                                                                                                                                                                    <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
                                                                                                                                                                                                                                                                              {FEATURES.map((feature) => {
                                                                                                                                                                                                                                                                                          const Icon = feature.icon;

                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                    key={feature.title}
                                                                                                                                                                                                                                                                                                                                                    className="rounded-2xl border border-brand-border bg-white p-8 shadow-sm transition-all duration-300 hover:-translate-y-2 hover:shadow-xl"
                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                  <div className="mb-5 inline-flex rounded-xl bg-brand-gold/10 p-4">
                                                                                                                                                                                                                                                                                                                                                                                                    <Icon className="h-7 w-7 text-brand-gold" />
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-xl font-semibold text-brand-emerald">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      {feature.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="mt-4 text-sm leading-7 text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {feature.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
